# domain: ansible.github.io
# url: https://ansible.github.io
# baseurl: /ansible-ui/
# name: ''
# title: null
# remote_theme: pages-themes/midnight
# plugins:
#   - jekyll-remote-theme # add this line to the plugins list if you already have one
