name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease

concurrency: main

jobs:
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

      - name: NPM Version - ${{ inputs.version || 'patch' }}
        run: |
          VERSION=`npm version ${{ inputs.version || 'patch' }} --no-git-tag-version`
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Git Commit Version and Push
        run: |
          git add --all
          git commit -m "${{ env.VERSION }} [skip ci]"
          git push origin --all

      - name: Git Tag Version and Push
        run: |
          git commit --allow-empty -m ${{ env.VERSION }}
          git tag -m ${{ env.VERSION }} ${{ env.VERSION }}
          git push origin --tags
