name: Main

on:
  push:
    branches:
      - main

concurrency: main

jobs:
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    timeout-minutes: 2

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Version
        run: npm version patch --no-git-tag-version

      - name: Git Push
        run: |
          git push origin --all
          git push origin --tags
