name: Main

on:
  push:
    branches:
      - main

concurrency: main

jobs:
  tag:
    name: Tag Release
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - id: version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          npm version patch

      - name: Git Push
        run: |
          git push origin --all
          git push origin --tags
