name: Pull Request
on:
    pull_request:
        branches: main
jobs:
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '18'
                  cache: 'npm'
            - run: npm ci
            - run: npm test
            - uses: romeovs/lcov-reporter-action@v0.2.16
              with:
                  lcov-file: ./coverage/lcov.info
